account/urls.py
from django.contrib.auth import views
from django.urls import path, include
from .views import *



app_name = 'account'
urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path('register/', Register.as_view(), name='register'),
    # path('activate/<uidb64>/<token>/', activate, name='activate'),
    path(
        "password_change/", PasswordChange.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),name="password_reset_done",),

    path('', include('django.contrib.auth.urls')),

    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('verify/', UserRegisterVerifyCodeView.as_view(), name='verify_code'),


]

urlpatterns += [
    path('', home, name='home'),
    path('user_selected_courses/', user_selected_courses, name='user_selected_courses'),
    path('profile/', profile, name='profile'),
    path('employees/', EmployeeListView.as_view(), name='employee-list'),
    path('jam_about/', jam_about, name='jam_about'),



]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('account/', include('account.urls')),
    path('', include('django.contrib.auth.urls')),
    path('gallery/', include('gallery.urls')),
    path('post/', include('posts.urls')),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('captcha/', include('captcha.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from .views import *

app_name = "course"
urlpatterns = [
    path('', home, name='home'),
    path('course/<int:id>', detail, name='detail'),
    path('conect/', conect, name='conect'),
    path('choices/', choices, name='choices'),
    path('create_course/', create_course, name='create_course'),
    path('delete_course/<int:id>/', delete_course, name='delete_course'),
    path('export-courses/', export_courses_to_excel, name='export_courses_to_excel'),
    path('export-all-courses/', all_courses_to_excel, name='all_courses_to_excel'),
    path('amozeshgayeazad/',free_school, name='free_school'),
    path('complaint_form/',complaint, name='complaint'),


]

gallery/urls.py
from django.urls import path
from .views import add_gallery_item, slide_detail,galleries

app_name = 'gallery'

urlpatterns = [
    path('add/', add_gallery_item, name='image_gallery'),
    path('slide/<int:id>/', slide_detail, name='slide_detail'),
    path('galleries/', galleries, name='galleries'),
]

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import create_post, posts, post

app_name = 'posts'

urlpatterns = [
    path('create_posts/', create_post, name='create'),
    path('list_posts/', posts, name='list'),
    path('post/<int:id>', post, name='post')
]

course/forms.py
from django import forms
from course.models import Course, Conect
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget
from captcha.fields import CaptchaField

class ContectForm(forms.ModelForm):
    messages = {
        "required": 'لطفا این فیلد را پر کنید',
    }

    class Meta:
        model = Conect
        exclude = [ 'subject', 'mehvar']
        fields = ['first_lastname', 'national_code', 'phone_number', 'title', 'text', 'relationship','captcha']


    RELATIONSHIP_CHOICES = (
        ('rm', 'رییس مرکز'),
        ('ka', 'کارشناس آموزش'),
        ('ki', 'کارشناس it'),
        ('ma', 'معاون آموزش'),
        ('em', 'ارتباط با مربیان'),
    )
    captcha = CaptchaField()
    first_lastname = forms.CharField(label='نام و نام خانوادگی', error_messages=messages)
    national_code = forms.CharField(label='کدملی', error_messages=messages)
    phone_number = forms.CharField(label='شماره تماس', error_messages=messages)
    title = forms.CharField(label='موضوع', error_messages=messages)
    text = forms.CharField(label='متن پیام', error_messages=messages, widget=forms.Textarea)
    relationship = forms.ChoiceField(label='ارتباط با', error_messages=messages, choices=RELATIONSHIP_CHOICES)


#   فرم شکایت---------------------------
class ComplaintForm(forms.ModelForm):
    messages = {
        "required": 'لطفا این فیلد را پر کنید',
    }
    SUBJECT_CHOICES = (
        ('sh', 'شکایت'),
        ('da', 'درخواست'),
        ('en', 'انتقاد'),

    )
    MEHVAR_CHOICES = (
        ('ma', 'مالی'),
        ('ed', 'اداری'),
        ('am', 'آموزش'),
        ('sa', 'سنجش و گواهینامه'),
        ('ta', 'تکریم ارباب رجوع'),

    )
    class Meta:
        model = Conect
        exclude = [ 'relationship']
        fields = ['first_lastname', 'national_code', 'phone_number', 'title', 'text', 'mehvar', 'subject','captcha']
        widgets = {'mehvar': forms.CheckboxSelectMultiple()}

    captcha = CaptchaField()
    first_lastname = forms.CharField(label='نام و نام خانوادگی', error_messages=messages)
    national_code = forms.CharField(label='کدملی', error_messages=messages)
    phone_number = forms.CharField(label='شماره تماس', error_messages=messages)
    title = forms.CharField(label='موضوع', error_messages=messages)
    text = forms.CharField(label='متن پیام', error_messages=messages, widget=forms.Textarea)
    mehvar = forms.MultipleChoiceField(label='محور شکایت', choices=MEHVAR_CHOICES, widget=forms.CheckboxSelectMultiple)
    subject = forms.ChoiceField(label='موضوع', error_messages=messages, choices=SUBJECT_CHOICES)

class ChoicesForm(forms.Form):
    GENDER_CHOICES = (
        ('w', 'مونث'),
        ('m', 'مذکر'),

    )
    course_id = forms.CharField(label='موضوع')
    gender = forms.ChoiceField(label='جنسیت', choices=GENDER_CHOICES)


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

    description = forms.CharField(max_length=700, widget=forms.Textarea)
    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.fields['start'] = JalaliDateField(label=('تاریخ شروع'), widget=AdminJalaliDateWidget)
        self.fields['end'] = JalaliDateField(label=('تاریخ پایان'), widget=AdminJalaliDateWidget)

course/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ContectForm, ChoicesForm, CourseForm, ComplaintForm
from .models import Course, Conect, Choes_cours, Free_school
from django.contrib import messages
from gallery.models import Image
from posts.models import Post
import pandas as pd
from django.http import HttpResponse
from jdatetime import datetime
from extension.utils import persian_number_converter
from datetime import date as datetimeen
from django_ratelimit.decorators import ratelimit
from openpyxl import Workbook
from openpyxl.styles import Alignment



# Create your views here.

# ----------------page home
@ratelimit(key='user_or_ip', rate='10/m')
def home(request):
    course_list = Course.objects.all().order_by('status')
    n = datetimeen.today()
    for o in course_list:
        if o.start > n:
            o.status = 'n'
        else:
            o.status = 'f'
    img_list = Image.objects.all()
    posts = Post.objects.all()
    paginator = Paginator(course_list, 8)
    page = request.GET.get('page')
    courses = paginator.get_page(page)
    current_date = persian_number_converter(str(datetime.now().strftime("%Y/%m/%d")))
    context = {
        "courses": courses,
        "img_list": img_list,
        'posts': posts,
        'current_date': current_date

    }
    return render(request, 'course/home.html', context)


# --------------detail cours
@login_required()
@ratelimit(key='user_or_ip', rate='10/m')
def detail(request, id):
    current_date = persian_number_converter(str(datetime.now().strftime("%Y/%m/%d")))
    context = {
        "course": get_object_or_404(Course, id=id, status='n'),
        'current_date': current_date
    }
    selected = Choes_cours.objects.filter(user_id=request.user.id, cours_id=context['course'].id)
    if selected.exists():
        context['selected'] = selected.get()

    if request.user.is_authenticated:
        return render(request, 'course/detail.html', context)

    return redirect('account:login')


# --------ارتباط با مسولین---------
@ratelimit(key='user_or_ip', rate='10/m')
def conect(request):
    if request.method == 'POST':
        form = ContectForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            national_code = form.cleaned_data.get('national_code')
            user_national_code = request.user.national_code
            user_phone_number = request.user.phone_number

            if phone_number != user_phone_number:
                form.add_error('phone_number', 'شماره تلفن وارد شده باید با شماره تلفن ثبت نام شما مطابقت داشته باشد.')
                return render(request, 'course/conect.html', {'form': form})
            if national_code != user_national_code:
                form.add_error('national_code', 'کد ملی وارد شده باید با کد ملی ثبت نام شما مطابقت داشته باشد.')
                return render(request, 'course/conect.html', {'form': form})
            cd = form.cleaned_data
            Conect.objects.create(title=cd['title'], text=cd['text'], first_lastname=cd['first_lastname'],
                                  relationship=cd['relationship'],
                                  user=request.user)
            messages.success(request, "پیام شما ارسال شد")
            return redirect('course:conect')

        else:
            messages.error(request, "پیام شما ارسال نشد,لطفا دوباره امتحان کنید.")

            return render(request, 'course/conect.html', {'form': form})


    else:
        form = ContectForm()

    return render(request, 'course/conect.html', {'form': form})


# _____________form shekayat ___________
@ratelimit(key='user_or_ip', rate='10/m')
def complaint(request):
    if request.method == 'POST':
        form = ComplaintForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            national_code = form.cleaned_data.get('national_code')
            user_national_code = request.user.national_code
            user_phone_number = request.user.phone_number

            if phone_number != user_phone_number:
                form.add_error('phone_number', 'شماره تلفن وارد شده باید با شماره تلفن ثبت نام شما مطابقت داشته باشد.')
                return render(request, 'course/complaint_form.html', {'form': form})
            if national_code != user_national_code:
                form.add_error('national_code', 'کد ملی وارد شده باید با کد ملی ثبت نام شما مطابقت داشته باشد.')
                return render(request, 'course/complaint_form.html', {'form': form})
            cd = form.cleaned_data
            Conect.objects.create(title=cd['title'], text=cd['text'], user=request.user,
                                  first_lastname=cd['first_lastname'], subject=cd['subject'],
                                  mehvar=cd['mehvar']
                                  )
            messages.success(request, "پیام شما ارسال شد")
            return redirect('course:complaint')

        else:
            messages.error(request, "پیام شما ارسال نشد,لطفا دوباره امتحان کنید.")

            return render(request, 'course/complaint_form.html', {'form': form})


    else:
        form = ContectForm()

    return render(request, 'course/complaint_form.html', {'form': form})


@ratelimit(key='user_or_ip', rate='10/m')
def choices(request):
    if request.method == 'POST':
        form = ChoicesForm(request.POST)

        if form.is_valid() or True:
            cd = form.cleaned_data
            Choes_cours.objects.create(cours_id=int(cd['course_id']), user_id=request.user.id)

            return redirect('course:home')

        return redirect('course:home')


@ratelimit(key='user_or_ip', rate='10/m')
def user_selected_courses(request):
    if request.user.is_authenticated:
        user_courses = Choes_cours.objects.filter(user=request.user)

        context = {
            'user_courses': user_courses,
            'selected': True
        }

        return render(request, 'registration/choice.html', context)


# ------حذف درس----------
@ratelimit(key='user_or_ip', rate='10/m')
def delete_course(request, id):
    user_courses = Choes_cours.objects.filter(id=id)

    if user_courses.exists():
        user_course = user_courses.first()
        user_course.delete()

    return redirect('course:home')


# -----ساخت درس توسط
@ratelimit(key='user_or_ip', rate='10/m')
def create_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            start_time = form.cleaned_data['start']
            end_time = form.cleaned_data['end']

            if end_time <= start_time:
                messages.error(request, "زمان پایان دوره باید بعد از زمان شروع باشد.")
            else:
                form.save()
                messages.success(request, "کلاس شما ایجاد شد.")
                return redirect('course:create_course')
        else:
            messages.error(request, "لطفا دوباره امتحان کنید. ")
    else:
        form = CourseForm()

    return render(request, 'course/create_course.html', {'form': form})


# ------دریافت لیست دروس اتخابی کلاینت---
@ratelimit(key='user_or_ip', rate='10/m')
def export_courses_to_excel(request):
    courses = Choes_cours.objects.all()

    if not courses:
        return HttpResponse("هیچ دوره‌ای برای صدور یافت نشد.")

    lst = []
    for o in courses:
        jalali_selection_time = datetime.fromgregorian(datetime=o.selection_time).strftime('%Y/%m/%d')
        lst.append({
            'ردیف': len(lst) + 1,
            'نام': o.user.username,
            'نام خانوادگی': o.user.last_name,
            'کدملی': o.user.national_code,
            'شماره تماس': o.user.phone_number,
            'نام دوره': o.cours.title,
            'زمان انتخاب': jalali_selection_time,

        })
    # تبدیل QuerySet به دیتافریم pandas
    # courses_df = pd.DataFrame(list(courses.values()))
    courses_df = pd.DataFrame(lst)

    # نام فایل Excel
    excel_file_name = 'registered_courses.xlsx'

    writer = pd.ExcelWriter(excel_file_name, engine='openpyxl')
    courses_df.to_excel(writer, index=False, sheet_name='Sheet1')

    # دریافت شیت openpyxl از نویسنده
    workbook = writer.book
    worksheet = writer.sheets['Sheet1']


    # تنظیمات زبان و چینش متن در اکسل
    worksheet.sheet_view.rightToLeft = True
    for row in worksheet.iter_rows():
        for cell in row:
            cell.alignment = Alignment(horizontal='right')

    workbook.save(excel_file_name)

    with open(excel_file_name, 'rb') as excel_file:
        response = HttpResponse(excel_file.read(),
                                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = f'attachment; filename="{excel_file_name}"'

    return response


# ------دریافت لیست تمامی دروس ---
@ratelimit(key='user_or_ip', rate='10/m')
def all_courses_to_excel(request):

    courses = Course.objects.all()

    if not courses:
        return HttpResponse("هیچ دوره‌ای برای صدور یافت نشد.")

    lst = []
    for o in courses:
        jalali_start = datetime.fromgregorian(datetime=o.start).strftime('%Y/%m/%d')
        jalali_end = datetime.fromgregorian(datetime=o.end).strftime('%Y/%m/%d')
        gender_display = 'زن' if o.gender == 'w' else 'مرد' if o.gender == 'm' else 'زن و مرد'
        lst.append({
            'ردیف': len(lst) + 1,
            'نام دوره': o.title,
            'مدرس': o.teacher,
            'کد درس': o.course_code,
            'تاریخ شروع': jalali_start,
            'تاریخ پایان': jalali_end,
            'نام مرکز دولتی': o.govermentcenter,
            'کارگاه/آموزشگاه': o.workshop,
            'جنسیت': gender_display,

        })

    courses_df = pd.DataFrame(lst)

    excel_file_name = 'all_courses.xlsx'
    writer = pd.ExcelWriter(excel_file_name, engine='openpyxl')

templates/course/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>فنی و حرفه ای</title>
    <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
    <link href="{% static 'gallery/css/gallery.css' %}" rel="stylesheet">
    <link href="{% static 'post/css/show-posts.css' %}" rel="stylesheet">
    <link href="{% static 'access/css/access.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">



</head>
<body>


{% include 'course/navbar.html' %}
    {% include 'includes/messages_block.html' %}

{% block gallery %}{% endblock %}
{% block access %}{% endblock %}
{% block features %}{% endblock %}
{% block excel %}{% endblock %}
{% include 'course/footer.html' %}
</body>
<script src="{% static 'gallery/js/gallery.js' %}"></script>
<script src="{% static 'course/js/menu.js' %}"></script>
<script src="{% static 'Exel/Exel.js' %}"></script>
<script src="{% static 'access/js/access-js.js' %}"></script>
<script src="{% static 'access/js/script.js' %}"></script>



</html>

templates/course/complaint_form.html
{% load widget_tweaks %}
{% load static %}

<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>فرم شکایت </title>
    <link href="{% static 'course/css/conect.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
</head>
<body>

<div>{% include 'course/navbar.html' with current_date=current_date %}</div>
<div>  {% include 'includes/messages_block.html' %}</div>
<div class="body">

    <div class="container_conect">
        <form action="" method="post" autocomplete="off" class="content-left" novalidate>
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div>
                    {% for error in form.non_field_errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="content-left-title">
                <h2 class="title">فرم شکایت</h2>

            </div>
            <div class="user-details">
                <div class="input-box">
                    <label class="detail">نام و نام خانوادگی:</label>
                    {{ form.first_lastname|add_class:"input" }}
                    {% if form.first_lastname.errors %}
                        <div class="error-message">
                            {{ form.first_lastname.errors }}
                        </div>
                    {% endif %}

                </div>
                <div class="input-box">
                    <label class="detail">کدملی:</label>
                    {{ form.national_code|add_class:"input" }}
                    {% if form.national_code.errors %}
                        <div class="error-message">
                            {{ form.national_code.errors }}
                        </div>
                    {% endif %}

                </div>
                <div class="mehvar_details">
                    <span class="mehvar_title">محور شکایت:</span>
                    <div class="category">
                        {% for value, label in form.mehvar.field.choices %}
                            <label>
                                <input type="checkbox" name="{{ form.mehvar.name }}" value="{{ value }}"
                                       {% if form.mehvar.value == value %}checked{% endif %} class="input">
                                {{ label }}
                            </label>
                        {% endfor %}
                    </div>
                </div>
                <div class="subject_details">
                    <span class="subject_title">موضوع:</span>
                    <div class="category">
                        {% for value, label in form.subject.field.choices %}
                            <label>
                                <input type="radio" name="{{ form.subject.name }}" value="{{ value }}"
                                       {% if form.subject.value == value %}checked{% endif %} class="input">
                                {{ label }}
                            </label>
                        {% endfor %}
                    </div>
                </div>

                <div class="input-box">
                    <label class="detail">شماره تماس:</label>
                    {{ form.phone_number|add_class:"input" }}
                    {% if form.phone_number.errors %}
                        <div class="error-message">
                            {{ form.phone_number.errors }}
                        </div>
                    {% endif %}

                </div>

                <div class="input-box">
                    <label class="detail">موضوع:</label>
                    {{ form.title|add_class:"input" }}
                    {% if form.title.errors %}
                        <div class="error-message">
                            {{ form.title.errors }}
                        </div>
                    {% endif %}

                </div>
                <div class="input-box">
                    <label class="detail">متن پیام:</label>
                    {{ form.text|add_class:"input1" }}
                    {% if form.text.errors %}
                        <div class="error-message">
                            {{ form.text.errors.0 }}
                        </div>
                    {% endif %}

                </div>
                {% include 'captcha/captcha.html' %}

                <input type="submit" value="ارسال" class="button">
            </div>
        </form>


    </div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

templates/course/detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="{% static 'course/css/detail.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'post/css/show-posts.css' %}" rel="stylesheet">

    <style>
        .circle {
            background: url('{{ course.thumbnail.url }}');
            background-size: cover;

        }
    </style>
</head>
<body>
{% include 'course/navbar.html' %}
<div class="body">
    <div class="container">
        <div class="circle"></div>
        <form method="post" action="{% url 'course:choices' %}" id="form">
            {% csrf_token %}


            <br>
            <h1>عنوان دوره:{{ course.title }}</h1>
            <p>
            <div class="teacher"> مدرس:{{ course.teacher }}</div>
            <br>
            <div> {{ course.picture }}</div>
            <br>
            <div>
                <div class="teacher">توضیحات:</div>
                {{ course.description|linebreaks }}</div>
            <br>
            <div>
                <div class="teacher"> تاریخ شروع:</div>
                {{ course.jstart }}</div>
            <br>
            <div>
                <div class="teacher">تاریخ پایان:</div>
                {{ course.jend }}</div>
            <br>
            <div>
                <div class="teacher">ساعت استاندارد:</div>
                {{ course.ptime }} ساعت
            </div>
            <br>
            <div>
                <div class="teacher">نام مرکز دولتی:</div>
                {{ course.govermentcenter }}</div>
            <br>
            <div>
                <div class="teacher">کارگاه/اموزشگاه:</div>
                {{ course.workshop }}</div>
            <br>
            <div>
                <div class="teacher">جنسیت کلاس:</div>
                {#            {{ course.gender }}#}
                {% if course.gender == 'w' %}
                    <span>زن</span>
                {% elif course.gender == 'm' %}
                    <span>مرد</span>
                {% elif course.gender == 'wm' %}
                    <span>زن و مرد</span>
                {% endif %}
            </div>
            <br>

            </p>


            <input type="hidden" name="course_id" value="{{ course.id }}">
            {% if selected %}



            {% else %}
                {% if user.gender in  course.gender %}
                    <button class="choice-course btn btn-primary" type="submit"> انتخاب درس</button>

                {% else %}
                    <label>این درس برای شما تعریف نشده است.</label>
                {% endif %}


            {% endif %}


        </form>
        {% if selected %}

            <button class="delete-course btn btn-secondary" data-course-id="{{ selected.id }}">حذف درس منتخب</button>


        {% endif %}


    </div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

<script src="{% static 'course/js/detail.js' %}"></script>

templates/course/navbar.html
{% load static %}
{% load base_tags %}
{#----------------navbar-------------------- #}
{% block navbar %}

    <div class="header_top">


        <img src="{% static 'course/img/سال.png' %}" alt="شعار سال" width="196"
             height="110" class="sal">

        <a class="logo" aria-label="title" target="_self">
            <img src="{% static 'gallery/svg/logo-animate_1.svg' %}" type="image/svg+xml" width="240"
                 height="116" alt="logo title">
        </a>


        <div class="header_top__left">
            <div class="date__today">

                تاریخ امروز: {{ current_date }}
            </div>
            <div class="account">
                <div>
                    {#<-----------login------------------->#}
                    {% if request.user.is_anonymous %}
                        <div class="logins">
                            <a class="icon" href="{% url 'account:login' %}">
                                ورود
                            </a>
                            <div class="slash">/</div>
                            <a class="icon" href="{% url 'account:register' %}">ثبت نام</a>

                        </div>
                    {% endif %}
                    <br>
                    {#<--------------------log out----------->#}
                    <form method="post" action="{% url 'account:logout' %}">
                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                            <button type="submit" id="svg">
                                <div class="logout">خروج</div>
                            </button>
                        {% endif %}
                    </form>


                </div>
                {% if request.user.is_authenticated %}

                    <a href="{% url 'account:password_change' %}">تغییر پسورد</a>


                {% endif %}
            </div>
        </div>


    </div>



    <header class="header">
        <div class="menubar">
            <img src="{% static 'course/svg/menu.svg' %}" class="menu">
            <a href="{% url 'course:home' %}" class="logo"><i class="fas fa-shopping-basket">مرکز فنی حرفه ای ۱۴ جم</i></a>
        </div>

        <nav class="navbar dropdown-menu">

            {% if request.user.is_authenticated %}

                <a href="{% url 'account:user_selected_courses' %}">دروس انتخابی</a>
                <a href="{% url 'course:conect' %}">ارتباط با مسولین</a>
                <a href="{% url 'account:profile' %}">پروفایل</a>
                {% if user.is_admin %}
                    <a href="{% url 'course:create_course' %}">ایجاد دوره</a>
                {% endif %}
                {#                                    <a href='{% url 'posts:list' %}'>پست ها</a>#}
                {#                                    <a href='{% url 'gallery:galleries' %}'>گالری</a>#}
                {#                                    <div href="#" class="about-us">درباره ما#}

            {% endif %}
            <a href='{% url 'posts:list' %}'>پست ها</a>
            <a href='{% url 'gallery:galleries' %}'>گالری</a>
            <div href="#" class="about-us">درباره ما


                <div class="submenu">
                    <li class="about_back" style="    text-align: center;
    padding-top: 10px;
    color: #ffffff;
    background: #04216787;
    padding-bottom: 1;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    flex-direction: row-reverse;
    gap: 18px;"
                    >
                        درباره ما
                        <img src="{% static 'course/svg/back.svg' %}" style="width: 17%;height: 88%;">
                    </li>
                    <li>
                        <a href="{% url 'account:employee-list' %}">لیست کارمندان</a>
                    </li>
                    <li>
                        <a href="{% url 'account:jam_about' %}">آموزشگاه دولتی</a>
                    </li>
                    <li>
                        <a href="{% url 'course:free_school' %}">آموزشگاه آزاد</a>
                    </li>

                </div>
            </div>


        </nav>
        </a>
        <div class="icons">


        </div>
    </header>
    <script src="{% static 'course/js/menu.js' %}"></script>
{% endblock %}