config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('account/', include('account.urls')),
    path('', include('django.contrib.auth.urls')),
    path('gallery/', include('gallery.urls')),
    path('post/', include('posts.urls')),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('captcha/', include('captcha.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import create_post, posts, post

app_name = 'posts'

urlpatterns = [
    path('create_posts/', create_post, name='create'),
    path('list_posts/', posts, name='list'),
    path('post/<int:id>', post, name='post')
]

posts/models.py
from django.db import models
from account.models import User
from extension.utils import jalali_converter, persian_number_converter






# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    thumbnail = models.ImageField(verbose_name="تصویر", blank=True, default=None)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "پست"
        verbose_name_plural = 'پست ها'

    def jcreated_at(self):
        return jalali_converter(self.created_at)

    jcreated_at.short_description = 'تاریخ ساخت'

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=100, required=True)
    content = forms.CharField(widget=forms.Textarea,required=True)
    thumbnail = forms.ImageField(required=True)
    class Meta:
        model = Post
        fields = ['title', 'content','thumbnail']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostForm
from jdatetime import datetime
from extension.utils import persian_number_converter
from django.contrib import messages
from django_ratelimit.decorators import ratelimit

# Create your views here.


@login_required
@ratelimit(key='user_or_ip', rate='10/m')
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            messages.success(request, "پست شما با موفقیت آپلود شد.", 'success')
            return redirect('posts:create')
        else:
            messages.error(request, "متاسفانه پست شما با موفقیت آپلود نشد.لطفا مجددا تلاش کنید.", 'error')
    else:
        form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})

@ratelimit(key='user_or_ip', rate='10/m')
def posts(request):
    current_date = persian_number_converter(str(datetime.now().strftime("%Y/%m/%d")))
    posts_list = Post.objects.all().order_by('-created_at')
    context = {
        'post_list': posts_list,
        'current_date': current_date
    }
    return render(request, 'posts/detail-posts.html', context)

@ratelimit(key='user_or_ip', rate='10/m')
def post(request, id):
    current_date = persian_number_converter(str(datetime.now().strftime("%Y/%m/%d")))
    context = {
        'current_date': current_date,
        'post': get_object_or_404(Post, id=id)
    }
    selected=Post.objects.filter(id=context['post'].id)
    if selected.exists():
        context['selected'] = selected.get()
        return render(request, 'posts/detail-post.html', context)

templates/posts/create_post.html
{% load static %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="{% static 'post/css/creat-post.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
       <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">


    <title>ایجاد پست</title>
</head>
<body>
<div>{% include 'course/navbar.html' with current_date=current_date %}</div>
<div>  {% include 'includes/messages_block.html' %}</div>
<div class="cont">
<div class="body">


    <div class="container">

        <div class="title">پست</div>
        <form method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div>
                    {% for error in form.non_field_errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="user-details">


                <div class="input-box">
                    <span class="detail">تصویر:</span>
                  {{ form.thumbnail|add_class:'input' }}
                    {% if form.thumbnail.errors %}
                        <div class="error_message">
                            {{ form.thumbnail.errors }}
                        </div>
                    {% endif %}


                </div>

                <br>


                <div class="input-box">

                    <span class="detail">عنوان:</span>
                    {{ form.title|add_class:'input' }}
                    {% if form.title.errors %}
                        <div class="error_message">
                            {{ form.title.errors }}
                        </div>
                    {% endif %}
                </div>

                <br>


                <div class="input-box">
                    <span class="detail">توضیحات:</span>

                    {{ form.content|add_class:'input00' }}

                    {% if form.content.errors %}
                        <div class="error_message">
                            {{ form.content.errors }}
                        </div>
                    {% endif %}
                </div>
                <br>


                <div class="button">
                   <button type="submit">آپلود</button>
                </div>


            </div>
        </form>

    </div>
</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

templates/posts/detail-post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
        <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
        <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
        <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
        <link href="{% static 'post/css/detail-post.css' %}" rel="stylesheet">
</head>
<body>
{% include 'course/navbar.html' %}
<div class="container">
<div class="title">{{ post.title }}</div>
<div class="content">{{ post.content|linebreaks }}</div>
<img src="{{ post.thumbnail.url }}" alt="{{ post.title }}">
<div class="created_at ">{{ post.jcreated_at}}</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

templates/posts/detail-posts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>پست ها</title>
        <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
        <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
        <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
        <link href="{% static 'post/css/list_post.css' %}" rel="stylesheet">
</head>
<body>
{% include 'course/navbar.html' %}
<div class="body">
<div class="container_post">
{% for post in post_list %}
    <div class="conten_post">
    <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}" class="img">
        <div class="flex">
<a class="title" href="{% url 'posts:post' post.id %}">{{ post.title|truncatewords:10 }}</a>


<div class="created_at ">{{ post.jcreated_at}}</div></div></div>
   {% endfor %}
</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>