config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('account/', include('account.urls')),
    path('', include('django.contrib.auth.urls')),
    path('gallery/', include('gallery.urls')),
    path('post/', include('posts.urls')),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('captcha/', include('captcha.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from .views import *

app_name = "course"
urlpatterns = [
    path('', home, name='home'),
    path('course/<int:id>', detail, name='detail'),
    path('conect/', conect, name='conect'),
    path('choices/', choices, name='choices'),
    path('create_course/', create_course, name='create_course'),
    path('delete_course/<int:id>/', delete_course, name='delete_course'),
    path('export-courses/', export_courses_to_excel, name='export_courses_to_excel'),
    path('export-all-courses/', all_courses_to_excel, name='all_courses_to_excel'),
    path('amozeshgayeazad/',free_school, name='free_school'),
    path('complaint_form/',complaint, name='complaint'),


]

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import create_post, posts, post

app_name = 'posts'

urlpatterns = [
    path('create_posts/', create_post, name='create'),
    path('list_posts/', posts, name='list'),
    path('post/<int:id>', post, name='post')
]

templates/access/free_school.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>دروس انتخاب شده</title>
    <link rel="stylesheet" href="{% static 'course/css/choice.css' %}">
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">

</head>
<body>
<main class="table">
    <section class="table_header">
        <a href="{% url 'course:home' %}" class="logo"><i class="fas fa-shopping-basket">مرکز فنی حرفه ای ۱۴ جم</i></a>
        <h>آموزشگاه های آزاد جم</h>
    </section>
    <section class="table_body">

        <table>
            <thead>
            <tr>

                <th>نام آموزشگاه</th>
                <th>نام موسس</th>
                <th>تلفن تماس</th>
                <th>رشته آموزشی</th>
                <th>جنسیت کارآموز</th>
                <th>آدرس</th>
                <th>موقعیت مکانی در نقشه</th>

            </tr>
            </thead>
            <tbody>
            {% for academy in academy_list %}
                <tr>
                    <td>{{ academy.name }}</td>

                    <td>{{ academy.founder }}</td>
                    <td>{{ academy.phone_number }}</td>
                    <td>{{ academy.field }}</td>
                    {% if academy.gender == 'w' %}
                        <td>زن</td>
                    {% elif academy.gender == 'm' %}
                        <td>مرد</td>
                    {% elif academy.gender == 'wm' %}
                        <td>زن و مرد</td>
                    {% endif %}

                    <td>{{ academy.address }}</td>
                    <td> <a href="{{ academy.location_link }}"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z"></path>
              <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z"></path>
            </svg></a></td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>

</main>
</body>
</html>