config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('account/', include('account.urls')),
    path('', include('django.contrib.auth.urls')),
    path('gallery/', include('gallery.urls')),
    path('post/', include('posts.urls')),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('captcha/', include('captcha.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from .views import add_gallery_item, slide_detail,galleries

app_name = 'gallery'

urlpatterns = [
    path('add/', add_gallery_item, name='image_gallery'),
    path('slide/<int:id>/', slide_detail, name='slide_detail'),
    path('galleries/', galleries, name='galleries'),
]

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import create_post, posts, post

app_name = 'posts'

urlpatterns = [
    path('create_posts/', create_post, name='create'),
    path('list_posts/', posts, name='list'),
    path('post/<int:id>', post, name='post')
]

gallery/models.py
from django.db import models


# Create your models here.
class Image(models.Model):
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.title

gallery/forms.py
from django import forms
from .models import Image


class GalleryItemForm(forms.ModelForm):
    title = forms.CharField(max_length=100, required=True)
    description = forms.CharField(widget=forms.Textarea,required=True)
    image = forms.ImageField(required=True)
    class Meta:
        model = Image
        fields = ['title', 'description', 'image']

gallery/views.py
from django.shortcuts import render, redirect
from .models import Image
from .forms import GalleryItemForm
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from extension.utils import persian_number_converter
from jdatetime import datetime
from django_ratelimit.decorators import ratelimit

# Create your views here.


@ratelimit(key='user_or_ip', rate='10/m')
def add_gallery_item(request):
    if request.method == 'POST':
        form = GalleryItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "عکس شما با موفقیت آپلود شد.", 'success')
            return redirect('gallery:image_gallery')
        else:
            messages.error(request, "متاسفانه وعکس شما با موفقیت آپلود نشد.لطفا مجددا تلاش کنید.", 'error')


    else:
        form = GalleryItemForm()


    return render(request, 'gallery/add_img.html', {'form': form})



@ratelimit(key='user_or_ip', rate='10/m')
def galleries(request):
    current_date = persian_number_converter(str(datetime.now().strftime("%Y/%m/%d")))
    gallery_list = Image.objects.all()
    context = {
        'gallery_list': gallery_list,
        'current_date': current_date
    }
    return render(request, 'gallery/detailimgs.html', context)





@ratelimit(key='user_or_ip', rate='10/m')
def slide_detail(request, id):
    current_date = persian_number_converter(str(datetime.now().strftime("%Y/%m/%d")))
    image = get_object_or_404(Image, pk=id)
    context={
        'current_date': current_date,
        'image': image
    }

    return render(request, 'gallery/slide_detail.html', context)

templates/gallery/add_img.html
{% load static %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="{% static 'gallery/css/add_img.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
   <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">

    <title>آپلود تصویر جدید</title>
</head>
<body>
<div>{% include 'course/navbar.html' with current_date=current_date %}</div>
<div>  {% include 'includes/messages_block.html' %}</div>
<div class="cont">

<div class="body">

    <div class="container">

        <div class="title">گالری</div>
        <form method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div>
                    {% for error in form.non_field_errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="user-details">


                <div class="input-box">
                    <span class="detail">تصویر:</span>
                    {{ form.image|add_class:'input' }}
                    {% if form.image.errors %}
                        <div class="error_message">
                            {{ form.image.errors }}
                        </div>
                    {% endif %}


                </div>

                <br>


                <div class="input-box">

                    <span class="detail">عنوان:</span>
                    {{ form.title|add_class:'input' }}
                    {% if form.title.errors %}
                        <div class="error_message">
                            {{ form.title.errors }}
                        </div>
                    {% endif %}
                </div>

                <br>


                <div class="input-box">
                    <span class="detail">توضیحات:</span>

                    {{ form.description|add_class:'input00' }}

                    {% if form.description.errors %}
                        <div class="error_message">
                            {{ form.description.errors }}
                        </div>
                    {% endif %}
                </div>
                <br>


                <div class="button">
                   <button type="submit">آپلود</button>
                </div>


            </div>
        </form>

    </div>
</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

templates/gallery/detail-imgs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>گالری ها</title>
</head>
<body>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'post/css/list_post.css' %}" rel="stylesheet">
</head>
<body>
{% include 'course/navbar.html' %}
<div class="body">
<div class="container_post">
    {% for gallery in gallery_list %}
        <div class="conten_post">
            <img src="{{ gallery.image.url }}" alt="{{ gallery.title }}" class="img">
            <div class="flex">
                <a class="title"
                   href="{% url 'gallery:slide_detail' gallery.id %}">{{ gallery.title|truncatewords:10 }}</a>


            </div>
        </div>
    {% endfor %}
</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

templates/gallery/detailimgs.html
{% load static %}
<!DOCTYPE html>

<html lang="en">


<head>
    <meta charset="UTF-8">
        <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>گالری ها</title>
    <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'post/css/list_post.css' %}" rel="stylesheet">
</head>
<body>
{% include 'course/navbar.html' %}
<div class="body">
<div class="container_post">
    {% for gallery in gallery_list %}
        <div class="conten_post">
            <img src="{{ gallery.image.url }}" alt="{{ gallery.title }}" class="img">
            <div class="flex">
                <a class="title"
                   href="{% url 'gallery:slide_detail' gallery.id %}">{{ gallery.title|truncatewords:10 }}</a>


            </div>
        </div>
    {% endfor %}
</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>

templates/gallery/slide_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ image.title }}</title>
        <link href="{% static 'gallery/css/slide_detail.css' %}" rel="stylesheet">
        <link href="{% static 'course/css/rtl.css' %}" rel="stylesheet">
    <link href="{% static 'course/css/home.css' %}" rel="stylesheet">
        <link href="{% static 'course/css/footer.css' %}" rel="stylesheet">
</head>
<body>{% include 'course/navbar.html' with current_date=current_date %}
<div class="gallery">


<div class="container">

    <h1 class="title">{{ image.title|linebreaks }}</h1>

    {% if image.image %}
        <img src="{{ image.image.url }}" alt="{{ image.title }}">
    {% endif %}

    <p>{{ image.description|linebreaks }}</p>
</div>
</div>
{% include 'course/footer.html' %}
</body>
</html>